// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/events": {
            "get": {
                "description": "Récupère les événements iCal pour une liste d'agendas, avec filtre optionnel sur une plage de dates.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Lister les événements",
                "parameters": [
                    {
                        "type": "string",
                        "description": "IDs d'agendas séparés par des virgules",
                        "name": "agendaIds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date début (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date fin (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Event"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Cherche l'événement dans le flux iCal (agendaIds requis).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Obtenir un événement par ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UID iCal de l'événement",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "\"123,456\"",
                        "description": "IDs d'agendas séparés par des virgules",
                        "name": "agendaIds",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/models.APIError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.APIError": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "agendaIds": {
                    "description": "resources used to fetch",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "DESCRIPTION (raw text)",
                    "type": "string"
                },
                "end": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "id": {
                    "description": "iCal UID",
                    "type": "string"
                },
                "lastUpdate": {
                    "description": "LAST-MODIFIED (RFC3339)",
                    "type": "string"
                },
                "location": {
                    "description": "LOCATION",
                    "type": "string"
                },
                "start": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "title": {
                    "description": "SUMMARY",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "API TIMETABLE",
	Description:      "API de lecture des évènements (iCal) de l'UCA.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
